### ISSUE TITLE
Auth review

### ISSUE THREAD

**Issue by humormee** [humormee/VeryBrite#2]
@jmeyer90

**Comment by jmeyer90** [comment]
User Auth Review

* We must have a demo login button for one-click login.
* Part of auth includes the navbar we use to navigate to our auth pages. Please render and style your navbar for when users are both logged out and logged in.
* Include an image on the right-hand side of the screen on the login and signup pages.
* Errors should clear when switching between the login and signup forms.

**Comment by humormee** [comment]
still need to implement drop down menu and fix error messages but 'mostly' styled. I will return to this mvp this weekend

**Comment by jmeyer90** [comment]
Most of our functionality looks good! However, I was not able to login as a demo user in Heroku. We may have to migrate and seed our Heroku database.
We also need to render errors. However, this can be done at a later time along with styling.

**Comment by humormee** [comment]
@jmeyer90 nav bar completed

**Comment by jmeyer90** [comment]
Hi Justin, Auth is completed! Feel free to move on to your next MVP. Please know that some touch-ups may be required later in the job search. But these will be minor fixes and are not a priority at this point in time. Great job!
